version: '2'
services:
  phpserver:
    build: ./docker/php
    volumes:
      - C:\Users\Jason\Documents\project1\app:/var/www/html
      - C:\Users\Jason\Documents\project1\vendor:/var/www/vendor
      - C:\Users\Jason\Documents\project1\src:/var/www/src
    links:
      - mysqlserver
      - redisserver
  mysqlserver:
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: dockerfordevs
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - /var/lib/mysql
    ports:
    - "3306:3306"
  redisserver:
    image: redis
    volumes:
      - /data
    ports:
    - "6379:6379"
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - phpserver
